export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const CREATE_GROUP_SUCCESSFUL = 'CREATE_GROUP_SUCCESSFUL';
export const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';
// export const LOAD_CATS_SUCCESS = 'LOAD_CATS_SUCCESS';
// export const LOAD_HOBBIES_SUCCESS = 'LOAD_HOBBIES_SUCCESS';
// export const UPDATE_CAT_SUCCESS = 'UPDATE_CAT_SUCCESS';
// export const CREATE_CAT_SUCCESS = 'CREATE_CAT_SUCCESS';
