export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const CREATE_GROUP_SUCCESSFUL = 'CREATE_GROUP_SUCCESSFUL';
export const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';
export const SIGNED_UP = 'SIGNED_UP';
export const REMOVE_SIGN_UP_MESSAGE = 'REMOVE_SIGN_UP_MESSAGE';
