export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const SIGN_OUT_SUCCESSFUL = 'SIGN_OUT_SUCCESSFUL';
export const CREATE_GROUP_SUCCESSFUL = 'CREATE_GROUP_SUCCESSFUL';
export const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';
export const RETRIEVE_GROUP_SUCCESSFUL = 'RETRIEVE_GROUP_SUCCESSFUL';
export const RETRIEVE_USERS_SUCCESSFUL = 'RETRIEVE_USERS_SUCCESSFUL';
